# Generated by Django 5.2.4 on 2025-07-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ALERT', 'Alert'), ('RECOMMENDATION', 'Recommendation')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, help_text='Optional: For region-specific alerts.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity in percentage', max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, help_text='Rainfall in mm', max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in km/h', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_conditions', to='recommendations.region')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
    ]
